<div class="col-m-4">
    <fieldset class="fieldset admin__fieldset " id="theme">
   	 <div class="admin__field field" data-ui-id="theme-edit-tabstab-general-section-fieldset-element-form-field-theme-path">
   		 <label class="label admin__field-label">
   			 <span>Label</span>
   		 </label>
   		 <div class="admin__field-control control">
   			 <div class="control-value">A value</div>
   		 </div>
   	 </div>
   	 <div class="admin__field field ">
   		 <label class="label admin__field-label" for="test_input">
   			 <span>Test input</span>
   		 </label>
   		 <div class="admin__field-control control">
   			 <input name="design[test_input]" id="test_input" value="" title="Test input" type="text" class="input-text admin__control-text" />
   		 </div>
   	 </div>
    </fieldset>
</div>