<div class="col-m-4">
    <table class="admin__table-secondary">
   	 <tr>
   		 <th><?php echo __('First name') ?></th>
   		 <td>John</td>
   	 </tr>
   	 <tr>
   		 <th><?php echo __('Last name') ?></th>
   		 <td>Doe</td>
   	 </tr>
   	 <tr>
   		 <th><?php echo __('Email') ?></th>
   		 <td>john.doe@example.com</td>
   	 </tr>
   	 <tr>
   		 <th><?php echo __('Phone') ?></th>
   		 <td>000 000 000</td>
   	 </tr>
    </table>
</div>