<div class="container">
	<form method='POST' action="/magento1/blog/index/save">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name">
	    </div>

	    <div class="form-group">
	        <label for="phone">Url Key</label>
	        <input type="text" class="form-control" id="url" placeholder="Enter a phone" name="url">
	    </div>
	    <div class="form-group">
	        <label for="organization">Content</label>
	        <input type="text" class="form-control" id="content" placeholder="Enter a organization" name="content">
	    </div>
	    <div class="form-group">
	        <label for="phone">Status</label>
	        <input type="text" class="form-control" id="status" placeholder="Enter a phone" name="status">
	    </div>
	    <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
	</form>
</div>